package com.petcity.pickme.common.utils;

import java.util.ArrayList;
import java.util.List;

/**
 * @ClassName DogBreedUtil
 * @Description TODO
 * @Author sherily
 * @Date 16/01/21 5:49 PM
 * @Version 1.0
 */
public class DogBreedUtil {
    public static List<String> CreateDogBreed() {
        List<String> dogBreeds = new ArrayList<>();
        dogBreeds.add("Afador");
        dogBreeds.add("Affenhuahua");
        dogBreeds.add("Affenpinscher");
        dogBreeds.add("Afghan Hound");
        dogBreeds.add("Airedale Terrier");
        dogBreeds.add("Akbash");
        dogBreeds.add("Akita");
        dogBreeds.add("Akita Chow");
        dogBreeds.add("Akita Pit");
        dogBreeds.add("Akita Shepherd");
        dogBreeds.add("Alaskan Klee Kai");
        dogBreeds.add("Alaskan Malamute");
        dogBreeds.add("American Bulldog");
        dogBreeds.add("American English Coonhound");
        dogBreeds.add("American Eskimo Dog");
        dogBreeds.add("American Foxhound");
        dogBreeds.add("American Hairless Terrier");
        dogBreeds.add("American Leopard Hound");
        dogBreeds.add("American Pit Bull Terrier");
        dogBreeds.add("American Pugabull");
        dogBreeds.add("American Staffordshire Terrier");
        dogBreeds.add("American Water Spaniel");
        dogBreeds.add("Anatolian Shepherd Dog");
        dogBreeds.add("Appenzeller Sennenhunde");
        dogBreeds.add("Auggie");
        dogBreeds.add("Aussiedoodle");
        dogBreeds.add("Aussiepom");
        dogBreeds.add("Australian Cattle Dog");
        dogBreeds.add("Australian Kelpie");
        dogBreeds.add("Australian Retriever");
        dogBreeds.add("Australian Shepherd");
        dogBreeds.add("Australian Shepherd Husky");
        dogBreeds.add("Australian Shepherd Lab Mix");
        dogBreeds.add("Australian Shepherd Pit Bull Mix");
        dogBreeds.add("Australian Stumpy Tail Cattle Dog");
        dogBreeds.add("Australian Terrier");
        dogBreeds.add("Azawakh");
        dogBreeds.add("Barbet");
        dogBreeds.add("Basenji");
        dogBreeds.add("Bassador");
        dogBreeds.add("Basset Fauve de Bretagne");
        dogBreeds.add("Basset Hound");
        dogBreeds.add("Basset Retriever");
        dogBreeds.add("Bavarian Mountain Scent Hound");
        dogBreeds.add("Beabull");
        dogBreeds.add("Beagle");
        dogBreeds.add("Beaglier");
        dogBreeds.add("Bearded Collie");
        dogBreeds.add("Bedlington Terrier");
        dogBreeds.add("Belgian Malinois");
        dogBreeds.add("Belgian Sheepdog");
        dogBreeds.add("Belgian Tervuren");
        dogBreeds.add("Bergamasco Sheepdog");
        dogBreeds.add("Berger Picard");
        dogBreeds.add("Bernedoodle");
        dogBreeds.add("Bernese Mountain Dog");
        dogBreeds.add("Bichon Frise");
        dogBreeds.add("Biewer Terrier");
        dogBreeds.add("Black and Tan Coonhound");
        dogBreeds.add("Black Mouth Cur");
        dogBreeds.add("Black Russian Terrier");
        dogBreeds.add("Bloodhound");
        dogBreeds.add("Blue Lacy");
        dogBreeds.add("Bluetick Coonhound");
        dogBreeds.add("Bocker");
        dogBreeds.add("Boerboel");
        dogBreeds.add("Boglen Terrier");
        dogBreeds.add("Bohemian Shepherd");
        dogBreeds.add("Bolognese");
        dogBreeds.add("Borador");
        dogBreeds.add("Border Collie");
        dogBreeds.add("Border Sheepdog");
        dogBreeds.add("Border Terrier");
        dogBreeds.add("Bordoodle");
        dogBreeds.add("Borzoi");
        dogBreeds.add("BoShih");
        dogBreeds.add("Bossie");
        dogBreeds.add("Boston Boxer");
        dogBreeds.add("Boston Terrier");
        dogBreeds.add("Bordoodle");
        dogBreeds.add("Borzoi");
        dogBreeds.add("BoShih");
        dogBreeds.add("Bossie");
        dogBreeds.add("Boston Boxer");
        dogBreeds.add("Boston Terrier");
        dogBreeds.add("Boston Terrier Pekingese Mix");
        dogBreeds.add("Bouvier des Flandres");
        dogBreeds.add("Boxador");
        dogBreeds.add("Boxer");
        dogBreeds.add("Boxerdoodle");
        dogBreeds.add("Boxmatian");
        dogBreeds.add("Boxweiler");
        dogBreeds.add("Boykin Spaniel");
        dogBreeds.add("Bracco Italiano");
        dogBreeds.add("Braque du Bourbonnais");
        dogBreeds.add("Briard");
        dogBreeds.add("Brittany");
        dogBreeds.add("Broholmer");
        dogBreeds.add("Brussels Griffon");
        dogBreeds.add("Bugg");
        dogBreeds.add("Bull-Pei");
        dogBreeds.add("Bull Terrier");
        dogBreeds.add("Bullador");
        dogBreeds.add("Bullboxer Pit");
        dogBreeds.add("Bulldog");
        dogBreeds.add("Bullmastiff");
        dogBreeds.add("Bullmatian");
        dogBreeds.add("Cairn Terrier");
        dogBreeds.add("Canaan Dog");
        dogBreeds.add("Cane Corso");
        dogBreeds.add("Cardigan Welsh Corgi");
        dogBreeds.add("Carolina Dog");
        dogBreeds.add("Catahoula Bulldog");
        dogBreeds.add("Catahoula Leopard Dog");
        dogBreeds.add("Caucasian Shepherd Dog");
        dogBreeds.add("Cav-a-Jack");
        dogBreeds.add("Cavachon");
        dogBreeds.add("Cavador");
        dogBreeds.add("Cavalier King Charles Spaniel");
        dogBreeds.add("Cavapoo");
        dogBreeds.add("Central Asian Shepherd Dog");
        dogBreeds.add("Cesky Terrier");
        dogBreeds.add("Chabrador");
        dogBreeds.add("Cheagle");
        dogBreeds.add("Chesapeake Bay Retriever");
        dogBreeds.add("Chi Chi");
        dogBreeds.add("Chi-Poo");
        dogBreeds.add("Chigi");
        dogBreeds.add("Chihuahua");
        dogBreeds.add("Chilier");
        dogBreeds.add("Chinese Crested");
        dogBreeds.add("Chinese Shar-Pei");
        dogBreeds.add("Chinook");
        dogBreeds.add("Chion");
        dogBreeds.add("Chipin");
        dogBreeds.add("Chiweenie");
        dogBreeds.add("Chorkie");
        dogBreeds.add("Chow Chow");
        dogBreeds.add("Chow Shepherd");
        dogBreeds.add("Chug");
        dogBreeds.add("Chusky");
        dogBreeds.add("Cirneco dell’Etna");
        dogBreeds.add("Clumber Spaniel");
        dogBreeds.add("Cockalier");
        dogBreeds.add("Cockapoo");
        dogBreeds.add("Cocker Spaniel");
        dogBreeds.add("Collie");
        dogBreeds.add("Corgi Inu");
        dogBreeds.add("Corgidor");
        dogBreeds.add("Corman Shepherd");
        dogBreeds.add("Coton de Tulear");
        dogBreeds.add("Croatian Sheepdog");
        dogBreeds.add("Curly-Coated Retriever");
        dogBreeds.add("Dachsador");
        dogBreeds.add("Dachshund");
        dogBreeds.add("Dalmatian");
        dogBreeds.add("Dandie Dinmont Terrier");
        dogBreeds.add("Daniff");
        dogBreeds.add("Danish-Swedish Farmdog");
        dogBreeds.add("Deutscher Wachtelhund");
        dogBreeds.add("Doberdor");
        dogBreeds.add("Doberman Pinscher");
        dogBreeds.add("Docker");
        dogBreeds.add("Dogo Argentino");
        dogBreeds.add("Dogue de Bordeaux");
        dogBreeds.add("Dorgi");
        dogBreeds.add("Dorkie");
        dogBreeds.add("Doxiepoo");
        dogBreeds.add("Doxle");
        dogBreeds.add("Drentsche Patrijshond");
        dogBreeds.add("Drever");
        dogBreeds.add("Dutch Shepherd");
        dogBreeds.add("English Cocker Spaniel");
        dogBreeds.add("English Foxhound");
        dogBreeds.add("English Setter");
        dogBreeds.add("English Springer Spaniel");
        dogBreeds.add("English Toy Spaniel");
        dogBreeds.add("Entlebucher Mountain Dog");
        dogBreeds.add("Estrela Mountain Dog");
        dogBreeds.add("Eurasier");
        dogBreeds.add("Field Spaniel");
        dogBreeds.add("Fila Brasileiro");
        dogBreeds.add("Finnish Lapphund");
        dogBreeds.add("Finnish Spitz");
        dogBreeds.add("Flat-Coated Retriever");
        dogBreeds.add("Fox Terrier");
        dogBreeds.add("French Bulldog");
        dogBreeds.add("French Bullhuahua");
        dogBreeds.add("French Spaniel");
        dogBreeds.add("Frenchton");
        dogBreeds.add("Frengle");
        dogBreeds.add("German Longhaired Pointer");
        dogBreeds.add("German Pinscher");
        dogBreeds.add("German Shepherd Dog");
        dogBreeds.add("German Shepherd Pit Bull");
        dogBreeds.add("German Shepherd Rottweiler Mix");
        dogBreeds.add("German Sheprador");
        dogBreeds.add("German Shorthaired Pointer");
        dogBreeds.add("German Spitz");
        dogBreeds.add("German Wirehaired Pointer");
        dogBreeds.add("Giant Schnauzer");
        dogBreeds.add("Glen of Imaal Terrier");
        dogBreeds.add("Goberian");
        dogBreeds.add("Goldador");
        dogBreeds.add("Golden Cocker Retriever");
        dogBreeds.add("Golden Mountain Dog");
        dogBreeds.add("Golden Retriever");
        dogBreeds.add("Golden Retriever Corgi");
        dogBreeds.add("Golden Shepherd");
        dogBreeds.add("Goldendoodle");
        dogBreeds.add("Gollie");
        dogBreeds.add("Gordon Setter");
        dogBreeds.add("Great Dane");
        dogBreeds.add("Great Pyrenees");
        dogBreeds.add("Greater Swiss Mountain Dog");
        dogBreeds.add("Greyador");
        dogBreeds.add("Greyhound");
        dogBreeds.add("Hamiltonstovare");
        dogBreeds.add("Hanoverian Scenthound");
        dogBreeds.add("Harrier");
        dogBreeds.add("Havanese");
        dogBreeds.add("Hokkaido");
        dogBreeds.add("Horgi");
        dogBreeds.add("Hovawart");
        dogBreeds.add("Huskita");
        dogBreeds.add("Huskydoodle");
        dogBreeds.add("Ibizan Hound");
        dogBreeds.add("Icelandic Sheepdog");
        dogBreeds.add("Irish Red And White Setter");
        dogBreeds.add("Irish Setter");
        dogBreeds.add("Irish Terrier");
        dogBreeds.add("Irish Water Spaniel");
        dogBreeds.add("Irish Wolfhound");
        dogBreeds.add("Italian Greyhound");
        dogBreeds.add("Jack-A-Poo");
        dogBreeds.add("Jack Chi");
        dogBreeds.add("Jack Russell Terrier");
        dogBreeds.add("Jackshund");
        dogBreeds.add("Japanese Chin");
        dogBreeds.add("Japanese Spitz");
        dogBreeds.add("Korean Jindo Dog");
        dogBreeds.add("Kai Ken");
        dogBreeds.add("Karelian Bear Dog");
        dogBreeds.add("Keeshond");
        dogBreeds.add("Kerry Blue Terrier");
        dogBreeds.add("King Shepherd");
        dogBreeds.add("Kishu Ken");
        dogBreeds.add("Komondor");
        dogBreeds.add("Kooikerhondje");
        dogBreeds.add("Kuvasz");
        dogBreeds.add("Kyi-Leo");
        dogBreeds.add("Lab Pointer");
        dogBreeds.add("Labernese");
        dogBreeds.add("Labmaraner");
        dogBreeds.add("Labrabull");
        dogBreeds.add("Labradane");
        dogBreeds.add("Labradoodle");
        dogBreeds.add("Labrador Retriever");
        dogBreeds.add("Labrastaff");
        dogBreeds.add("Labsky");
        dogBreeds.add("Lagotto Romagnolo");
        dogBreeds.add("Lakeland Terrier");
        dogBreeds.add("Lancashire Heeler");
        dogBreeds.add("Leonberger");
        dogBreeds.add("Lhasa Apso");
        dogBreeds.add("Lhasapoo");
        dogBreeds.add("Lowchen");
        dogBreeds.add("Maltese");
        dogBreeds.add("Maltese Shih Tzu");
        dogBreeds.add("Maltipoo");
        dogBreeds.add("Manchester Terrier");
        dogBreeds.add("Mastador");
        dogBreeds.add("Mastiff");
        dogBreeds.add("Miniature Pinscher");
        dogBreeds.add("Miniature Schnauzer");
        dogBreeds.add("Morkie");
        dogBreeds.add("Mudi");
        dogBreeds.add("Mutt (Mixed)");
        dogBreeds.add("Neapolitan Mastiff");
        dogBreeds.add("Newfoundland");
        dogBreeds.add("New Zealand Heading Dog");
        dogBreeds.add("Norfolk Terrier");
        dogBreeds.add("Northern Inuit Dog");
        dogBreeds.add("Norwegian Buhund");
        dogBreeds.add("Norwegian Elkhound");
        dogBreeds.add("Norwegian Lundehund");
        dogBreeds.add("Norwich Terrier");
        dogBreeds.add("Nova Scotia Duck Tolling Retriever");
        dogBreeds.add("Old English Sheepdog");
        dogBreeds.add("Otterhound");
        dogBreeds.add("Papillon");
        dogBreeds.add("Papipoo");
        dogBreeds.add("Patterdale Terrier");
        dogBreeds.add("Peekapoo");
        dogBreeds.add("Pekingese");
        dogBreeds.add("Pembroke Welsh Corgi");
        dogBreeds.add("Petit Basset Griffon Vendéen");
        dogBreeds.add("Pharaoh Hound");
        dogBreeds.add("Pitsky");
        dogBreeds.add("Plott");
        dogBreeds.add("Pocket Beagle");
        dogBreeds.add("Pointer");
        dogBreeds.add("Polish Lowland Sheepdog");
        dogBreeds.add("Pomapoo");
        dogBreeds.add("Pomchi");
        dogBreeds.add("Pomeagle");
        dogBreeds.add("Pomeranian");
        dogBreeds.add("Pomsky");
        dogBreeds.add("Poochon");
        dogBreeds.add("Poodle");
        dogBreeds.add("Portuguese Podengo Pequeno");
        dogBreeds.add("Portuguese Sheepdog");
        dogBreeds.add("Portuguese Water Dog");
        dogBreeds.add("Pug");
        dogBreeds.add("Pugalier");
        dogBreeds.add("Puggle");
        dogBreeds.add("Puginese");
        dogBreeds.add("Puli");
        dogBreeds.add("Pyredoodle");
        dogBreeds.add("Pyrenean Mastiff");
        dogBreeds.add("Pyrenean Shepherd");
        dogBreeds.add("Rat Terrier");
        dogBreeds.add("Redbone Coonhound");
        dogBreeds.add("Rhodesian Ridgeback");
        dogBreeds.add("Rottador");
        dogBreeds.add("Rottle");
        dogBreeds.add("Rottweiler");
        dogBreeds.add("Saint Berdoodle");
        dogBreeds.add("Saint Bernard");
        dogBreeds.add("Saluki");
        dogBreeds.add("Samoyed");
        dogBreeds.add("Samusky");
        dogBreeds.add("Schipperke");
        dogBreeds.add("Schnoodle");
        dogBreeds.add("Scottish Deerhound");
        dogBreeds.add("Scottish Terrier");
        dogBreeds.add("Sealyham Terrier");
        dogBreeds.add("Sheepadoodle");
        dogBreeds.add("Shepsky");
        dogBreeds.add("Shetland Sheepdog");
        dogBreeds.add("Shiba Inu");
        dogBreeds.add("Shichon");
        dogBreeds.add("Shih-Poo");
        dogBreeds.add("Shih Tzu");
        dogBreeds.add("Shiloh Shepherd");
        dogBreeds.add("Shiranian");
        dogBreeds.add("Shollie");
        dogBreeds.add("Shorkie");
        dogBreeds.add("Siberian Husky");
        dogBreeds.add("Silken Windhound");
        dogBreeds.add("Silky Terrier");
        dogBreeds.add("Skye Terrier");
        dogBreeds.add("Sloughi");
        dogBreeds.add("Small Munsterlander Pointer");
        dogBreeds.add("Soft Coated Wheaten Terrier");
        dogBreeds.add("Spanish Mastiff");
        dogBreeds.add("Spinone Italiano");
        dogBreeds.add("Springador");
        dogBreeds.add("Stabyhoun");
        dogBreeds.add("Staffordshire Bull Terrier");
        dogBreeds.add("Staffy Bull Bullmastiff");
        dogBreeds.add("Standard Schnauzer");
        dogBreeds.add("Sussex Spaniel");
        dogBreeds.add("Swedish Lapphund");
        dogBreeds.add("Swedish Vallhund");
        dogBreeds.add("Taiwan Dog");
        dogBreeds.add("Terripoo");
        dogBreeds.add("Texas Heeler");
        dogBreeds.add("Tibetan Mastiff");
        dogBreeds.add("Tibetan Spaniel");
        dogBreeds.add("Tibetan Terrier");
        dogBreeds.add("Toy Fox Terrier");
        dogBreeds.add("Transylvanian Hound");
        dogBreeds.add("Treeing Tennessee Brindle");
        dogBreeds.add("Treeing Walker Coonhound");
        dogBreeds.add("Valley Bulldog");
        dogBreeds.add("Vizsla");
        dogBreeds.add("Weimaraner");
        dogBreeds.add("Welsh Springer Spaniel");
        dogBreeds.add("Welsh Terrier");
        dogBreeds.add("West Highland White Terrier");
        dogBreeds.add("Westiepoo");
        dogBreeds.add("Whippet");
        dogBreeds.add("Whoodle");
        dogBreeds.add("Wirehaired Pointing Griffon");
        dogBreeds.add("Xoloitzcuintli");
        dogBreeds.add("Yorkipoo");
        dogBreeds.add("Yorkshire Terrier");
        dogBreeds.add("Other");
        return dogBreeds;
    }
}
